apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{NAME}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: {{IMAGE}}
        ports:
        - containerPort: 80
