apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dxr-csm-cgallreleaseswitch-issues-test
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # When scaling to zero - last pod will be terminated after x sec.
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "0s"
        # Max. number of pods
        autoscaling.knative.dev/max-scale: "100"
        # Scale to zero
        autoscaling.knative.dev/min-scale: "0"
        # Whith Container concurrency of 1 after 0.7 (70% is default) pods a new is started 
        autoscaling.knative.dev/target-utilization-percentage: "100"
    spec:
      # Max. in-flight-requests per pod.
      containerConcurrency: 1
      # Max execution time for pod to respond (hard limit)
      timeoutSeconds: 240
      imagePullSecrets:
      - name: regcred
      containers:
      - image: 920852828576.dkr.ecr.eu-west-1.amazonaws.com/hsi-model-demo:dxr.csm.cgallreleaseswitch.issues.test
        env:
          - name: ISverticaUsername
            valueFrom:
              configMapKeyRef:
                name: secrets-configmap
                key: ISverticaUsername
          - name: ISverticaPassword
            valueFrom:
              configMapKeyRef:
                name: secrets-configmap
                key: ISverticaPassword
        resources:
          requests:
            cpu: 10m
            memory: 50m
          limits:
            cpu: 500m
            memory: 2Gi # container is killed if reaches this value
        ports:
        - containerPort: 8080
