name: Deploy to EKS

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Configure AWS CLI
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} > aws_access_key
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} > aws_secret_key
          aws configure set aws_access_key_id $(cat aws_access_key)
          aws configure set aws_secret_access_key $(cat aws_secret_key)
      
      # - name: Build Docker Image
      #   run: docker build -t my-image:${{ github.sha }} .
  
      - name: Login to ECR
        id: ecr-login
        env : 
          tag : my-image:${{ github.sha }}
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${{ github.sha }} .
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${{ github.sha }}
      - name: Deploy to EKS
        run: |
          sed -i "s|{{NAME}}|${{ secrets.K8S_DEPLOYMENT_NAME }}|g" k8s/deployment.yaml
          sed -i "s|{{IMAGE}}|${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${{ github.sha }}|g" k8s/deployment.yaml
          kubectl apply -f k8s/deployment.yaml
